# Generated by Django 3.1.7 on 2021-04-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20210427_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='expense_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
