# Generated by Django 3.1.7 on 2021-05-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20210430_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='expense',
            name='product',
            field=models.ManyToManyField(null=True, to='budget.Product'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.ManyToManyField(null=True, to='budget.Event'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ManyToManyField(null=True, to='budget.Category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
