# Generated by Django 3.1.7 on 2021-05-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20210504_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='product',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='product',
            field=models.ManyToManyField(null=True, to='budget.Product'),
        ),
    ]
