# Generated by Django 3.1.7 on 2021-05-07 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_auto_20210504_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='product',
        ),
        migrations.AddField(
            model_name='expense',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.product'),
        ),
    ]
