from django.urls import path
from . import views
from .forms import AddEventForm
from .forms import AddExpenseForm

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('products/', views.products, name='products'),
    path('product/<str:product>/', views.product, name='product'),
    path('subcategories/', views.subcategories, name='subcategories'),
    path('subcategory/<str:subcategory>/', views.subcategory, name='subcategory'),
    path('categories/', views.categories, name='categories'),
    path('category/<str:category>/', views.category, name='category'),
    path('expenses/', views.expenses, name='expenses'),
    path('expense/<str:expense>/', views.expense, name='expense'),
    path('events/', views.events, name='events'),
    path('event/<str:event>/', views.event, name='event'),
    path('delete/', views.delete, name='delete'),
    path('del_products/', views.del_products, name='del_products'),
    path('del_subcategories/', views.del_subcategories, name='del_subcategories'),
    path('del_categories/', views.del_categories, name='del_categories'),
    path('del_expenses/', views.del_expenses, name='del_expenses'),
    path('del_events/', views.del_events, name='del_events'),
    path('import_all/', views.import_all, name='import_all'),
    path('import_products/', views.import_products, name='import_products'),
    path('import_categories/', views.import_categories, name='import_categories'),
    path('import_subcategories/', views.import_subcategories, name='import_subcategories'),
    path('import_expenses/', views.import_expenses, name='import_expenses'),
    path('import_events/', views.import_events, name='import_events'),
    # path('add_event/', views.add_event, name='add_event'),
    path('add_event/', views.FormWizardView.as_view([AddEventForm, AddExpenseForm])),
    # path('plot/', views.plot, name='plot'),
    # path('plot2/', views.plot2, name='plot2'),
    # path('plot3/', views.plot3, name='plot3'),
    # path('plot4/', views.plot4, name='plot4'),
    # path('plot5/', views.plot5, name='plot5'),
    # path('plot6/', views.plot6, name='plot6'),
    path('plot_product/', views.plot_product, name='plot_product'),
    path('plot_expenses/', views.plot_expenses, name='plot_expenses'),
    path('plot_product_bar/', views.plot_product_bar, name='plot_product_bar'),
    path('plots/', views.plots, name='plots'),
]
